server:
  port: 20887

  
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak: 
            authorizationGrantType: authorization_code
            client-id: oauth2-client-app
            client-name: oauth2-client-app
            client-secret: WOK6puaB91PpJFuFonHke8hbE2oYoilG
            redirect-uri: http://localhost:20887/login/oauth2/code/keycloak
            clientAuthenticationMethod: client_secret_post
            scope: openid, profile, email
        provider: 
          keycloak: 
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/oauth2
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            toekn-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username